name: develop-build

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-test-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetch all tags and reflog for master/develop
      run: |
        git fetch --tags
        git branch --create-reflog master origin/master
        git branch --create-reflog develop origin/develop
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Compute GitVersion
      uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""
    - name: Update version in nuspec
      run: sed -e "s/GITVERSION/$(cat version.txt)/" SacredSkull.TidalUSDK/SacredSkull.TidalUSDK.nuspec
    - name: Build with dotnet
      run: dotnet build -c Release -v minimal
    - name: Unit Tests
      run: dotnet test
    - name: Pack NuGet
      run: dotnet pack -c Release
    - uses: actions/upload-artifact@master
      with:
        name: TidalUSDK-release
        path: SacredSkull.TidalUSDK/bin/Release/
  test-windows:
    needs: [build-test-ubuntu]
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Unit tests
      run: dotnet test
