name: dotnet

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Compute GitVersion
      uses: docker://gittools/gitversion:5.0.2-beta1-27-linux-centos-7-netcoreapp2.2
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c \"echo $GitVersion_FullSemVer > /github/workspace/version.txt\""
    - name: Update version in nuspec
      run: sed -e "s/GITVERSION/$(cat version.txt)/" SacredSkull.TidalUSDK/SacredSkull.TidalUSDK.nuspec
    - name: Build with dotnet
      run: dotnet build -c Release -v detailed
    - name: Unit Tests
      run: dotnet test
    - name: Pack NuGet
      run: dotnet pack -c Release
    - uses: actions/upload-artifact@master
      with:
        name: TidalUSDK-release
        path: SacredSkull.TidalUSDK/bin/Release/
  test:
    needs: [build]
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Unit Tests
      run: dotnet test
