name: master-release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Pack release
      run: dotnet pack -c Release SacredSkull.TidalUSDKR
    - name: Publish NuGet
      run: cd SacredSkull.TidalUSDK/bin/Release/ && for pkg in *.nupkg; do dotnet nuget push $pkg -k $nuget_api_key https://api.nuget.org/v3/index.json; done
      env:
        nuget_api_key: ${{ secrets.NugetApiKey }}