name: master-release

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Pack release
      run: dotnet pack -c Release TidalUSDKR
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - name: Publish NuGet
      run: cd TidalUSDK/bin/Release/ && for pkg in *.nupkg; do dotnet nuget push $pkg -k $nuget_api_key -s https://api.nuget.org/v3/index.json; done
      env:
        nuget_api_key: ${{ secrets.NugetApiKey }}